name: rw_camera
description: Camera Plugin for RealWear HMT-1(Z1)
version: 1.0.0
homepage: https://github.com/Skyggedans/rw_camera

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.rockwellits.rw_plugins.rw_camera
    pluginClass: RwCameraPlugin
